### ISSUE TITLE
前辈能不能出一节Nginx+uwsgi部署的视频

### ISSUE THREAD

**Issue by My-captain** [HaddyYang/django2.0-course#4]
我把11年的老博客都翻出来了还是没部署成功

**Comment by HaddyYang** [comment]
@My-captain 下次课就是了，哈哈

**Comment by HaddyYang** [comment]
@My-captain https://www.bilibili.com/video/av31456425 忘记发链接给你了，这个链接就是Nginx的

**Comment by My-captain** [comment]
谢谢！ @HaddyYang
