### ISSUE TITLE
mysql 连接错误

### ISSUE THREAD

**Issue by fxyan** [HaddyYang/django2.0-course#7]
你好 我已开始按照您的mysql设置是可以连接并且使用的但是今天再次连接的时候出现了错误
ERROR 2026 (HY000): SSL connection error: error:00000000:lib(0):func(0):reason(0)

**Comment by HaddyYang** [comment]
@fxyan 我查了一下，看到这个，看看是否有帮助。
https://stackoverflow.com/questions/31413031/mysql-error-2026-hy000-ssl-connection-error-error00000001lib0func0re  
这里，他用了一条命令 mysql --user=root --password=test testdb --skip-ssl

**Comment by fxyan** [comment]
好的  我也查到了这个但是还是失败了，不知道什么原因，现在我从新下了一个安装版的MySQL经过千辛万苦把它装到我的电脑上了...........为什么软件安装这么多坑
