### ISSUE TITLE
第25节课ajax会跳转到json页面

### ISSUE THREAD

**Issue by FoSuCloud** [HaddyYang/django2.0-course#8]
第25节课ajax会跳转到json页面，对着老师的代码也没错啊，网友说script要写在jQuery之前是什么意思？

**Comment by HaddyYang** [comment]
1、检查jquery是否可以正常使用
2、考虑用event.preventDefault()方法，这个是取消默认提交行为

**Comment by FoSuCloud** [comment]
已经解决了，是jQuery问题，谢谢航哥，我现在看到部署准备（三），但是又有问题，我的项目可以运行，也用了80端口，设置了安全组，但是都是无法访问网页，求救！！！

在 2019-05-13 09:21:45，"杨仕航" <notifications@github.com> 写道：


1、检查jquery是否可以正常使用
2、考虑用event.preventDefault()方法，这个是取消默认提交行为
